# action.yml
name: 'EthicalCheck'
description: 'Free & Instant API Penetration Testing Service'
inputs:
  oas-url:
    description: 'The Open API Specification or public Postman collection URL.'
    required: true
    default: ''
  email:
    description: 'The email address to which the API penetration test report will be sent.'
    required: true
    default: '' 
 
runs:
  using: "composite"
  steps:
    - run:  ${GITHUB_ACTION_PATH}/pentest-script.sh "${{inputs.oas-url}}" "${{ inputs.email }}"  
      shell: bash
