# action.yml
name: 'APIsec Free Pentest'
description: 'Continuous, automated, comprehensive API Security Testing'
inputs:
  oas-url:
    description: 'The Open API Specification URL against which the scans will be executed.'
    required: true
    default: ''
  email:
    description: 'The email address on which the vulnerabilities report will be sent.'
    required: true
    default: '' 
 
runs:
  using: "composite"
  steps:
    - run:  ${GITHUB_ACTION_PATH}/apisec-run-scan.sh "${{inputs.oas-url}}" "${{ inputs.email }}"  
      shell: bash
